version: '3.9'

services:
  backend:
    build: "."
    restart: always
    ports:
      - "8080"
    deploy:
      replicas: 3
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    container_name: messaging_service_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - backend

volumes:
  db-data:
